# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=django.utils.datetime_safe.date.today, verbose_name='Date and Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='desc',
            field=models.TextField(default=django.utils.datetime_safe.date.today, max_length=10000, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Title'),
        ),
    ]
