# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 06:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20170920_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='projects.Project'),
        ),
    ]
