# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20171013_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletinpost',
            name='post_message',
            field=models.CharField(max_length=10000, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_desc',
            field=models.TextField(default='', max_length=10000, verbose_name='Project Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(default='', max_length=50, verbose_name='Project Name'),
        ),
    ]
