# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20170920_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletinpost',
            name='post_date',
            field=models.DateTimeField(verbose_name='Date Posted'),
        ),
    ]
