# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20170921_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='project_desc',
            field=models.CharField(default='Generic project description', max_length=10000),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(default='Generic project name', max_length=50),
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
