# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20170927_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_desc',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
