# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20170927_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Date Created'),
        ),
    ]
